### ISSUE TITLE
Error in 'Installation' commands

### ISSUE THREAD

**Issue by jerome-antoine** [Pavel-N/rpower#1]
Hi !
The 'Installation' part seems to contain a mistake: instead of 
make && sudo make install 
I think it should rather be 
cargo build --release ?
Thanks for your work !

**Comment by Pavel-N** [comment]
Hello, yes you are correct, since I was not using the Makefile much when developing, it appears I have missed this. I will fix it in a minute.

Also, stay tuned for new commits as I will (hopefully) update to newer version of the dependencies.
